apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: mysql-operator
      sourceRef:
        kind: HelmRepository
        name: mysql-operator
      version: 2.2.4
  interval: 10m0s
  targetNamespace: mysql-operator
  install:
    crds: Create
    createNamespace: true