apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: elastic-clustersecretstore
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from `default` namespace
      remoteNamespace: elastic-eck
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: elastic-eck
          key: ca.crt
      auth:
        serviceAccount:
          name: "local-secrets"
          namespace: elastic-eck