apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: elastic-secret-sharing-ca-elasticsearch
spec:
  namespaceSelector:
    matchLabels:
      elastic-eck/ca-elasticsearch: "true"
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      name: elastic-clustersecretstore
      kind: ClusterSecretStore
    refreshInterval: 1h
    target:
      name: elastic-ca-elasticsearch
      template:
        type: Opaque
        data:
          ca.crt: "{{ .ca | toString }}"
    data:
      - secretKey: ca
        remoteRef:
          key: elasticsearch-es-http-ca-internal
