apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: es-repo
  namespace: elastic-eck
spec:
  generateBucketName: es-repo
  storageClassName: rook-ceph-bucket
  additionalConfig:
    maxSize: "50G"
