apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
      version: 0.27.0
  interval: 10m0s
  targetNamespace: trivy-operator
  install:
    crds: Create
    createNamespace: true