apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: trivy-operator
      version: 0.28.0
  interval: 10m0s
  targetNamespace: trivy-operator
  install:
    crds: Create
    createNamespace: true
  values:
    serviceMonitor:
      enabled: true
    trivy:
      ignoreUnfixed: true
      ignorePolicy:
        jenkins: |
          package trivy
          import data.lib.trivy
          default ignore = false
          ignore_check_id := {"KSV053", "KSV048"}
          ignore {
            input.CweIDs == ignore_check_id[_]
          }