apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event-exporter
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '2112'
        prometheus.io/path: '/metrics'
    spec:
      serviceAccountName: event-exporter
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: event-exporter
          # The good practice would be to pin the version. This is just a reference so that we don't
          # have to update this file in each release.
          image: ghcr.io/resmoio/kubernetes-event-exporter:v1.7
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
            - name: elastic-ca-elasticsearch
              mountPath: /certificates/elasticsearch/
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://elasticsearch-es-http.elastic-eck:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-logging
                  key: username
                  optional: false
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-logging
                  key: password
                  optional: false
      volumes:
        - name: cfg
          configMap:
            name: event-exporter-cfg
        - name: elastic-ca-elasticsearch
          secret:
            secretName: elastic-ca-elasticsearch
  selector:
    matchLabels:
      app: event-exporter
      version: v1
