apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-bucket
  namespace: monitoring
spec:
  bucketName: ${THANOS_BUCKET_NAME}
  storageClassName: ceph-bucket
  additionalConfig:
    maxObjects: "1000000"
    maxSize: "100G"
