apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-status
  namespace: flux-system
spec:
  type: github
  address: https://github.com/SimonStiil/rke2-flux
  secretRef:
    name: github-flux-notifications-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github-status
  namespace: flux-system
spec:
  providerRef:
    name: github-status
  eventSources:
  - kind: Kustomization
    name: authentik
  - kind: Kustomization
    name: cert-manager
  - kind: Kustomization
    name: cilium-bgp
  - kind: Kustomization
    name: cloudnative-pg
  - kind: Kustomization
    name: crds-base
  - kind: Kustomization
    name: crds-cert-manager
  - kind: Kustomization
    name: crds-metallb
  - kind: Kustomization
    name: crds-rook
  - kind: Kustomization
    name: csi-driver-nfs
  - kind: Kustomization
    name: external-dns
  - kind: Kustomization
    name: external-secrets
  - kind: Kustomization
    name: flux-system
  - kind: Kustomization
    name: flux-system-additions-external-secrets
  - kind: Kustomization
    name: flux-system-additions-rook
  - kind: Kustomization
    name: flux-webhook
  - kind: Kustomization
    name: monitoring
  - kind: Kustomization
    name: reloader
  - kind: Kustomization
    name: rook-ceph
  - kind: Kustomization
    name: test
  - kind: Kustomization
    name: traefik
  - kind: Kustomization
    name: traefik-out-of-cluster
  - kind: HelmRelease
    name: authentik
  - kind: HelmRelease
    name: cert-manager
  - kind: HelmRelease
    name: cnpg
  - kind: HelmRelease
    name: csi-driver-nfs
  - kind: HelmRelease
    name: external-dns
  - kind: HelmRelease
    name: external-secrets
  - kind: HelmRelease
    name: kube-prometheus-stack
  - kind: HelmRelease
    name: loki
  - kind: HelmRelease
    name: prometheus-operator-crds
  - kind: HelmRelease
    name: promtail
  - kind: HelmRelease
    name: reloader
  - kind: HelmRelease
    name: rook-ceph-cluster
  - kind: HelmRelease
    name: rook-ceph-opperator
  - kind: HelmRelease
    name: traefik