---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.27.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 10m0s
  targetNamespace: cloudnative-pg
  install:
    createNamespace: true