---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.18.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-secrets
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: external-secrets
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
#    bitwarden-sdk-server:
#      enabled: true
    revisionHistoryLimit: 2
    webhook:
      revisionHistoryLimit: 2
    certController:
      revisionHistoryLimit: 2