apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: immich
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ceph-nvme