---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: "0.9.2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:

  chartRef:
    kind: OCIRepository
    name: immich
  interval: 10m0s
  targetNamespace: immich
  install:
    crds: Create
    createNamespace: true
  values:
    env:
      DB_HOSTNAME: "{{ .Release.Name }}-postgresql"
      DB_USERNAME: "{{ .Values.postgresql.global.postgresql.auth.username }}"
      DB_DATABASE_NAME: "{{ .Values.postgresql.global.postgresql.auth.database }}"
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim:
          
    server:
      ingress:
        main:
          enabled: true
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: images.tpi.stiil.dk
              paths:
                - path: "/"