---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-opperator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph
      version: v1.18.8
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 10m0s
  targetNamespace: rook-ceph
  values:
    csi:
      csiAddons:
        # -- Enable CSIAddons
        enabled: yes
      nfs:
        # -- Enable the nfs csi driver
        enabled: false
        
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true