apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-rook
  namespace: flux-system
spec:
  interval: 30m
  timeout: 1m
  path: ./crds/rook
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
