---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: cloudnative-pg-cnpg
    namespace: cloudnative-pg
  - apiVersion: v1
    kind: Service
    name: cnpg-webhook-service
    namespace: cloudnative-pg
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusters.postgresql.cnpg.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: databases.postgresql.cnpg.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: clusters.postgresql.cnpg.io
