---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./csi-driver-nfs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: csi-nfs-controller
    namespace: kube-system
  - apiVersion: apps/v1
    kind: DaemonSet
    name: csi-nfs-node
    namespace: kube-system
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    name: nfs-diskstation
---