---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rke-patches
  namespace: flux-system
spec:
  interval: 10m0s
  timeout: 5m
  path: ./rke-patches
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.cattle.io/v1
    kind: HelmChartConfig
    name: rke2-ingress-nginx
    namespace: kube-system
  postBuild:
    substitute:
      var_substitution_enabled: "true"
    substituteFrom:
      - kind: Secret
        name: clusterconfig
        optional: true
---