apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ldap-secret
  namespace: kube-auth-proxy
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: ldap-secret
    template:
      data:
        password: "{{ .password | toString }}"
  data:
  - secretKey: password
    remoteRef:
      key: ldap-kubeauth