
---
# ExternalSecret for Meilisearch Master Key
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-meilisearch
  namespace: linkwarden
spec:
  secretStoreRef:
    name: webhook-backend
    kind: ClusterSecretStore
  target:
    name: linkwarden-meilisearch
    creationPolicy: Owner
  data:
  - secretKey: MEILI_MASTER_KEY
    remoteRef:
      key: linkwarden-meilisearch-master-ke
      property: turingpi
---
# Flux HelmRelease for Meilisearch
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: meilisearch
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: meilisearch
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: meilisearch
  targetNamespace: linkwarden
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_ENV: production
    
    auth:
      existingMasterKeySecret: linkwarden-meilisearch
    
    persistence:
      enabled: true
      storageClass: ceph-block
      size: 5Gi