apiVersion: v1
kind: ConfigMap
metadata:
  name: gitconfig
  namespace: jenkins
data:
  .gitconfig: |
    [user]
            email = 130985998+SimonStiil@users.noreply.github.com
            name = simon
    [http]
            proxy = http://diskstation.${topleveldomain:=undefined}:3128