---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      version: 1.18.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: external-dns
  values:
    interval: 5m
    sources:
    - ingress
    policy: sync
    # -- (string) Specify an identifier for this instance of _ExternalDNS_ wWhen using a registry other than `noop`.
    txtOwnerId: ${clusterdomain:=undefined}
    # -- (string) Specify a prefix for the domain names of TXT records created for the `txt` registry.
    # Mutually exclusive with `txtSuffix`.
    txtPrefix: external-dns-
    domainFilters: 
    - ${topleveldomain}
    - ${homedomain}
    provider:
      # -- _ExternalDNS_ provider name; for the available providers and how to configure them see [README](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers).
      name: rfc2136
    extraArgs: 
    - --label-filter=external-dns-export=true
    - --rfc2136-host=192.168.10.15
    - --rfc2136-port=53
    - --rfc2136-zone=${topleveldomain}
    - --rfc2136-zone=${homedomain}
##    - --rfc2136-tsig-secret=96Ah/a2g0/nLeFGK+d/0tzQcccf9hCEIy34PoXX2Qg8=
##    - --rfc2136-tsig-secret-alg=hmac-sha256
##    - --rfc2136-tsig-keyname=externaldns-key
    - --rfc2136-insecure
    - --rfc2136-tsig-axfr